<?php
/**
* The Module Class
* @package Mars
*/

namespace Mars\Extensions\Modules;

use Mars\App;
use Mars\Content\ContentInterface;
use Mars\Extensions\Extension;
use Mars\Extensions\Extensions;
use Mars\Extensions\Abilities\ConfigTrait;
use Mars\Extensions\Abilities\FilesCacheTrait;
use Mars\Extensions\Abilities\LanguagesTrait;
use Mars\Extensions\Modules\Abilities\MvcTrait;
use Mars\Extensions\Modules\Abilities\TemplatesTrait;
use Mars\Http\Response\Body\Data\Data;
use Mars\Menus\Menu;

/**
 * The Module Class
 * Base class for all module extensions
 */
class Module extends Extension implements ContentInterface
{
    use FilesCacheTrait;
    use MvcTrait;
    use ConfigTrait;
    use LanguagesTrait;
    use TemplatesTrait;

    /**
     * @const array DIRS The locations of the used extensions subdirs
     */
    public const array DIRS = [
        ...parent::DIRS,
        'bin' => 'bin',
        'controllers' => 'Controllers',
        'models' => 'Models',
        'views' => 'Views',
        'pages' => 'pages',
        'plugins' => 'plugins'
    ];

    /**
     * @const array CACHE_DIRS The dirs to be cached
     */
    public const array CACHE_DIRS = ['templates'];

    /**
     * @var array $route_params The params passed to the module, if any
     */
    public protected(set) array $route_params = [];

    /**
     * @internal
     */
    public ?Extensions $manager {
        get => $this->app->modules;
    }

    /**
     * @internal
     */
    protected static string $type = 'module';

    /**
     * @internal
     */
    protected static string $base_dir = 'modules';

    /**
     * @internal
     */
    protected static string $base_namespace = "\\Modules";

    /**
     * Generates the output and returns it 
     * @param array $params The params to pass to the module, if any
     * @return Data The response data generated by the module
     */
    public function run(array $params = []) : Data
    {
        $this->route_params = $params;

        $this->app->timer->start('extension_output');

        ob_start();
        $ret = include($this->path . '/index.php');
        $content = ob_get_clean();

        $this->exec_time = $this->app->timer->stop('extension_output');

        return $this->app->response->body->create($ret, $content);
    }

    /**
     * Loads and executes the module controller
     * @return Data The response data generated by the module controller
     */
    public function execute() : Data
    {
        [$controller, $method] = $this->getAction();
        if (!$controller) {
            throw new \Exception("No controller defined for module {$this->name}");
        }

        $this->app->lang->setBaseKey(static::$type . '.' . $this->name . '.' . $controller);

        $controller = $this->getController($controller);
        $result = $controller->dispatch($method, $this->route_params);

        $this->app->lang->restoreBaseKey();

        return $result;
    }

    /**
     * Gets the action from the params
     * @return array An array with the controller name and method to be called
     */
    protected function getAction() : array
    {
        $action = $this->params['action'] ?? '';
        if (!$action) {
            return [null, null];
        }

        if (is_array($action)) {
            //convert the action array keys to lowercase, in case the request method was provided in uppercase
            $action = array_combine(array_map('strtolower', array_keys($action)), array_values($action));
            $method = $this->app->request->method;
            
            $my_action = $action[$method] ?? null;
            if ($my_action) {
                return $this->getControllerAndMethod($my_action);
            }
            //fallback to 'get' method, if an action for the current method is not defined
            if ($method != 'get') {
                $my_action = $action['get'] ?? null;
                if ($my_action) {
                    return $this->getControllerAndMethod($my_action);
                }
            }

        } else {
            return $this->getControllerAndMethod($action);
        }

        return [null, null];
    }

    /**
     * Gets the controller and method to be executed
     * @param string $action The action string
     * @return array An array with the controller name and method to be called
     */
    protected function getControllerAndMethod(string $action) : array
    {
        $parts = explode('@', $action);
        $controller = $parts[0] ?? null;
        $method = $parts[1] ?? null;

        return [$controller, $method];
    }

    /**
     * Called to collect the menu items for the module
     * @param Menu $menu The Menu to collect the items for
     * @return static
     */
    public function menu(Menu $menu) : static
    {
        $menu_file = $this->path . '/' . self::DIRS['menus'] . "/{$menu->type}.php";
        if (is_file($menu_file)) {
            include $menu_file;
        }

        return $this;
    }
}
