<?php
/**
 * The Extensions Sitemap Class
 * @package Mars
 */
namespace Mars\Seo\Sitemap;

use Mars\Extensions\Extension;
use Mars\Extensions\Extensions as ExtensionsManager;

/**
 * The Extensions Sitemap Class.
 * Class is responsible for generating sitemap XML files for the application's extensions.
 */
class Extensions extends Base
{
    /**
     * Generates the sitemap for the extensions
     * @return array The list of generated sitemap files
     */
    public function generate() : array
    {
        $sitemaps = [];

        $managers = $this->app->extensions->getManagers('sitemaps');
        
        foreach ($managers as $manager) {
            $extensions = $manager->getEnabled();
            
            foreach ($extensions as $name => $path) {
                $sitemap_path = $path . '/' . Extension::DIRS['sitemap'];
                if (!is_dir($sitemap_path)) {
                    continue;
                }

                $extension_sitemaps = $this->get($manager, $name, $sitemap_path);
                $sitemaps = array_merge($sitemaps, $extension_sitemaps);
            }
        }

        return $sitemaps;
    }

    /**
     * Returns the list of sitemap files generated by the specified extension
     * @param ExtensionsManager $manager The extensions manager instance
     * @param string $name The name of the extension
     * @param string $path The path to the extension's sitemap directory
     * @return array The list of sitemap files generated by the extension
     */
    protected function get(ExtensionsManager $manager, string $name, string $path) : array
    {
        $sitemaps = [];
        $classes = $this->app->getClasses($path, $manager->getBaseNamespace($name) . '\\Sitemap');

        foreach ($classes as $namespace => $filename) {
            include($filename);

            $object = new $namespace($this->app);
            $class_sitemaps = $object->generate();

            $sitemaps = array_merge($sitemaps, $class_sitemaps);
        }

        return $sitemaps;
    }
}
