<?php
/**
* The Content Interface
* @package Mars
*/

namespace Mars\Content;

use Mars\Http\Response\Body\Data\Data;

/**
 * The Content Interface
 */
interface ContentInterface
{
    /**
     * Generates the output and returns it 
     * @param array $vars Variables to pass to the content
     * @return Data The response data generated by the content
     */
    public function run(array $vars = []) : Data;
}