<?php
/**
* The Route Class
* @package Mars
*/

namespace Mars;

use Mars\App\LazyLoad;
use Mars\App\LazyLoadProperty;
use Mars\Http\Response\Body\Data\Data;
use Mars\Router\Base;
use Mars\Router\Loader;
use Mars\Router\Finder;
use Mars\Router\Dispatcher;

/**
 * The Router Class
 * Route handling class
 */
class Router extends Base
{
    use LazyLoad;

    /**
     * @var string $route The route used by the router
     */
    public protected(set) string $route {
        get {
            if (isset($this->route)) {
                return $this->route;
            }

            $this->route = $this->app->url->path;

            //remove the slashes, for all the routes except the root
            if ($this->route) {
                $this->route = trim($this->route, '/');
            } else {
                $this->route = '/';
            }

            return $this->route;
        }
    }

    /**
     * @var string $name The name of the matched route
     */
    public protected(set) string $name = '';

    /**
     * @var string $pattern The pattern of the matched route
     */
    public protected(set) string $pattern = '';

    /**
     * @var Loader $loader The routes loader
     */
    #[LazyLoadProperty]
    public protected(set) Loader $loader;

    /**
     * @var Finder $finder The routes finder
     */
    #[LazyLoadProperty]
    public protected(set) Finder $finder;

    /**
     * @var Dispatcher $dispatcher The routes dispatcher
     */
    #[LazyLoadProperty]
    public protected(set) Dispatcher $dispatcher;

    /**
     * The constructor
     * @param App|null $app The app object
     */
    public function __construct(?App $app = null)
    {
        parent::__construct($app);

        $this->lazyLoad($this->app);
    }

    /**
     * Outputs the content based on the matched route
     * @return Data The response data
     */
    public function execute() : Data
    {
        $route = $this->getRoute();
        if (!$route) {
            //try to get the 404 route, if exists
            $route = $this->getRoute('404');

            if (!$route) {
                $this->notFound();
            }
        }

        $this->name = $route[2]['name'] ?? '';
        $this->pattern = $route[2]['pattern'] ?? '';

        return $this->dispatch($route);
    }

    /**
     * Handles the 404 not found cases
     */
    public function notFound()
    {
        header('HTTP/1.0 404 Not Found', true, 404);
        die;
    }

    /**
     * Returns the route matching the current request
     * @param string|null $route The route to get the route for. If null, the current route will be used
     * @return array|null
     */
    protected function getRoute(?string $route = null) : array|null
    {
        //check if the method is allowed
        if (!in_array($this->app->request->method, static::ALLOWED_METHODS)) {
            return null;
        }

        $route ??= $this->route;
        $hash = $this->getHash($route);
        $hashes = $this->app->cache->routes->getHashes($this->app->request->method, $this->app->lang->code, $this->getPrefix($route));
        if (!$hashes) {
            return null;
        }

        return $this->finder->get($hash, $hashes);
    }

    /**
     * Dispatches the content generated by a route
     * @param array $route The route
     * @return Data The response data
     */
    protected function dispatch(array $route) : Data
    {
        [$action, $params] = $route;

        return $this->dispatcher->get($action, $params);
    }
}
